# Generated by Django 6.0.1 on 2026-03-04 15:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Engineering, Operations)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('head', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_mgmt_department',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='user_mgmt_d_name_30f84b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Module name (e.g., Sales & CRM, Inventory)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_mgmt_module',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='user_mgmt_m_name_8a28b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., Admin, Manager)', max_length=100, unique=True)),
                ('level', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('SUPERVISOR', 'Supervisor'), ('ANALYST', 'Analyst'), ('STAFF', 'Staff'), ('VIEWER', 'Viewer')], default='STAFF', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_mgmt_role',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['level'], name='user_mgmt_r_level_ceb9a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ERPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending Activation')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user_management.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user_management.role')),
            ],
            options={
                'db_table': 'user_mgmt_erpuser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_expires_days', models.IntegerField(default=90)),
                ('password_history_count', models.IntegerField(default=5)),
                ('require_special_characters', models.BooleanField(default=True)),
                ('two_factor_required', models.BooleanField(default=False)),
                ('two_factor_method', models.CharField(blank=True, choices=[('TOTP', 'TOTP'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=50, null=True)),
                ('session_timeout_minutes', models.IntegerField(default=15)),
                ('max_concurrent_sessions', models.IntegerField(default=3)),
                ('restrict_to_ip', models.BooleanField(default=False)),
                ('whitelisted_ips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_setting', to='user_management.erpuser')),
            ],
            options={
                'verbose_name': 'Security Setting',
                'verbose_name_plural': 'Security Settings',
                'db_table': 'user_mgmt_securitysetting',
            },
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('invitation_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.department')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to='user_management.erpuser')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.role')),
            ],
            options={
                'db_table': 'user_mgmt_userinvite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PERMISSION_CHANGE', 'Permission Changed'), ('ROLE_CHANGE', 'Role Changed'), ('PASSWORD_CHANGE', 'Password Changed'), ('2FA_ENABLE', '2FA Enabled'), ('2FA_DISABLE', '2FA Disabled'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='SUCCESS', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='user_management.erpuser')),
            ],
            options={
                'db_table': 'user_mgmt_activitylog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_mgmt_a_user_id_80055c_idx'), models.Index(fields=['action'], name='user_mgmt_a_action_98629c_idx'), models.Index(fields=['-timestamp'], name='user_mgmt_a_timesta_ac175e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user_management.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='user_management.erpuser')),
            ],
            options={
                'db_table': 'user_mgmt_permission',
                'ordering': ['module__name'],
                'indexes': [models.Index(fields=['user', 'module'], name='user_mgmt_p_user_id_d4dc17_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['username'], name='user_mgmt_e_usernam_589341_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['email'], name='user_mgmt_e_email_ca4984_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['status'], name='user_mgmt_e_status_50120f_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['department'], name='user_mgmt_e_departm_e5a907_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['role'], name='user_mgmt_e_role_id_74fb73_idx'),
        ),
        migrations.AddIndex(
            model_name='erpuser',
            index=models.Index(fields=['-last_login'], name='user_mgmt_e_last_lo_352724_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['email'], name='user_mgmt_u_email_0255bd_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['status'], name='user_mgmt_u_status_168e85_idx'),
        ),
        migrations.AddIndex(
            model_name='userinvite',
            index=models.Index(fields=['-expires_at'], name='user_mgmt_u_expires_fe38f2_idx'),
        ),
    ]
