# Generated by Django 6.0.1 on 2026-02-28 10:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAYROLL', 'Payroll'), ('MARKETING', 'Marketing'), ('RENT_UTILITIES', 'Rent & Utilities'), ('SUPPLIES', 'Supplies'), ('TECHNOLOGY', 'Technology'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], help_text='Expense category', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date when expense was incurred')),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'screen4_expense',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier', max_length=50, unique=True)),
                ('client_name', models.CharField(help_text='Name of the client', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Invoice amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Payment status of invoice', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Invoice creation date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'screen4_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Source of revenue (e.g., Product Sales, Service Income)', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Revenue amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField(help_text='Date when revenue was received')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'db_table': 'screen4_revenue',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_account_2815ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_account_8fba74_idx',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='screen4_exp_date_5d5943_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='screen4_exp_categor_15e934_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='screen4_exp_date_0190e8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='screen4_inv_invoice_fb9e58_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='screen4_inv_status_8269e0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='screen4_inv_created_27d684_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['date'], name='screen4_rev_date_87b793_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['source'], name='screen4_rev_source_c8528f_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['-date'], name='screen4_rev_date_c2b086_idx'),
        ),
    ]
