from decimal import Decimal


STATIONERY_PRODUCTS = [
    {"name": "A4 Copier Paper 70 GSM (500 Sheets)", "sku": "SA1", "category": "Stationary", "unit_price": Decimal("1450.00"), "stock_quantity": 220, "reorder_level": 40},
    {"name": "A4 Copier Paper 80 GSM (500 Sheets)", "sku": "SA2", "category": "Stationary", "unit_price": Decimal("1650.00"), "stock_quantity": 180, "reorder_level": 35},
    {"name": "A3 Copier Paper 80 GSM (500 Sheets)", "sku": "SA3", "category": "Stationary", "unit_price": Decimal("3250.00"), "stock_quantity": 90, "reorder_level": 18},
    {"name": "A4 Register 200 Pages", "sku": "SA4", "category": "Stationary", "unit_price": Decimal("280.00"), "stock_quantity": 260, "reorder_level": 50},
    {"name": "Notebook Small 100 Pages", "sku": "SA5", "category": "Stationary", "unit_price": Decimal("120.00"), "stock_quantity": 320, "reorder_level": 60},
    {"name": "Spiral Notebook A4", "sku": "SA6", "category": "Stationary", "unit_price": Decimal("390.00"), "stock_quantity": 140, "reorder_level": 25},
    {"name": "Ball Pen Blue (Pack of 10)", "sku": "SA7", "category": "Stationary", "unit_price": Decimal("350.00"), "stock_quantity": 450, "reorder_level": 80},
    {"name": "Ball Pen Black (Pack of 10)", "sku": "SA8", "category": "Stationary", "unit_price": Decimal("350.00"), "stock_quantity": 420, "reorder_level": 80},
    {"name": "Gel Pen (Pack of 5)", "sku": "SA9", "category": "Stationary", "unit_price": Decimal("290.00"), "stock_quantity": 260, "reorder_level": 45},
    {"name": "Pencil HB (Pack of 12)", "sku": "SA10", "category": "Stationary", "unit_price": Decimal("210.00"), "stock_quantity": 280, "reorder_level": 50},
    {"name": "Eraser Large", "sku": "SA11", "category": "Stationary", "unit_price": Decimal("55.00"), "stock_quantity": 320, "reorder_level": 60},
    {"name": "Sharpener Metal", "sku": "SA12", "category": "Stationary", "unit_price": Decimal("45.00"), "stock_quantity": 300, "reorder_level": 55},
    {"name": "Marker Permanent Black", "sku": "SA13", "category": "Stationary", "unit_price": Decimal("95.00"), "stock_quantity": 240, "reorder_level": 45},
    {"name": "Highlighter Set (4 Colors)", "sku": "SA14", "category": "Stationary", "unit_price": Decimal("420.00"), "stock_quantity": 120, "reorder_level": 24},
    {"name": "Whiteboard Marker (Pack of 4)", "sku": "SA15", "category": "Stationary", "unit_price": Decimal("420.00"), "stock_quantity": 110, "reorder_level": 22},
    {"name": "Sticky Notes 3x3", "sku": "SA16", "category": "Stationary", "unit_price": Decimal("180.00"), "stock_quantity": 210, "reorder_level": 40},
    {"name": "Glue Stick 36g", "sku": "SA17", "category": "Stationary", "unit_price": Decimal("110.00"), "stock_quantity": 190, "reorder_level": 35},
    {"name": "Liquid Glue 100ml", "sku": "SA18", "category": "Stationary", "unit_price": Decimal("160.00"), "stock_quantity": 170, "reorder_level": 30},
    {"name": "Stapler Medium", "sku": "SA19", "category": "Stationary", "unit_price": Decimal("420.00"), "stock_quantity": 95, "reorder_level": 18},
    {"name": "Stapler Pins No.10", "sku": "SA20", "category": "Stationary", "unit_price": Decimal("65.00"), "stock_quantity": 420, "reorder_level": 80},
    {"name": "Paper Clips Box", "sku": "SA21", "category": "Stationary", "unit_price": Decimal("95.00"), "stock_quantity": 260, "reorder_level": 45},
    {"name": "Binder Clips Assorted", "sku": "SA22", "category": "Stationary", "unit_price": Decimal("160.00"), "stock_quantity": 230, "reorder_level": 40},
    {"name": "Scissors 8 inch", "sku": "SA23", "category": "Stationary", "unit_price": Decimal("280.00"), "stock_quantity": 120, "reorder_level": 24},
    {"name": "Ruler 30cm", "sku": "SA24", "category": "Stationary", "unit_price": Decimal("80.00"), "stock_quantity": 220, "reorder_level": 40},
    {"name": "Brown Envelope A4", "sku": "SA25", "category": "Stationary", "unit_price": Decimal("28.00"), "stock_quantity": 650, "reorder_level": 120},
    {"name": "Brown Envelope Legal", "sku": "SA26", "category": "Stationary", "unit_price": Decimal("35.00"), "stock_quantity": 520, "reorder_level": 100},
    {"name": "Document File A4", "sku": "SA27", "category": "Stationary", "unit_price": Decimal("180.00"), "stock_quantity": 180, "reorder_level": 32},
    {"name": "Lever Arch File", "sku": "SA28", "category": "Stationary", "unit_price": Decimal("320.00"), "stock_quantity": 140, "reorder_level": 25},
    {"name": "Ring Binder A4", "sku": "SA29", "category": "Stationary", "unit_price": Decimal("360.00"), "stock_quantity": 130, "reorder_level": 24},
    {"name": "Index Divider Set", "sku": "SA30", "category": "Stationary", "unit_price": Decimal("140.00"), "stock_quantity": 160, "reorder_level": 30},
    {"name": "Packing Tape 2 inch", "sku": "SA31", "category": "Stationary", "unit_price": Decimal("210.00"), "stock_quantity": 260, "reorder_level": 45},
    {"name": "Tape Dispenser", "sku": "SA32", "category": "Stationary", "unit_price": Decimal("390.00"), "stock_quantity": 90, "reorder_level": 18},
    {"name": "Desk Organizer", "sku": "SA33", "category": "Stationary", "unit_price": Decimal("850.00"), "stock_quantity": 70, "reorder_level": 15},
    {"name": "Calculator 12 Digit", "sku": "SA34", "category": "Stationary", "unit_price": Decimal("980.00"), "stock_quantity": 80, "reorder_level": 16},
    {"name": "Punch Machine 2-Hole", "sku": "SA35", "category": "Stationary", "unit_price": Decimal("520.00"), "stock_quantity": 75, "reorder_level": 14},
    {"name": "Exam Board", "sku": "SA36", "category": "Stationary", "unit_price": Decimal("180.00"), "stock_quantity": 130, "reorder_level": 24},
]

